apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "stages"
spec:
  stages:
    - name: "pvs"
      sequences:
      - name: "delivery"
        tasks:
        - name: "test"
          properties:
            teststrategy: "functional"
        - name: "evaluation"